// Rich product types (decision D25): several variation dimensions, category-specific attributes, believable
// combinations. All names are invented: no real brands, processors or operating systems.
import type { AttrDef, TypeDef } from "./types";

const variation = (key: string, label: string, values: string[]): AttrDef => ({ key, label, role: "variation", facet: false, values });
const spec = (key: string, label: string, values: string[], facet = false): AttrDef => ({ key, label, role: "spec", facet, values });

export const RICH_TYPES: TypeDef[] = [
  {
    slug: "smartphones", name: "Smartphones", category: "electronics", shape: "phone", noun: "Smartphone",
    mods: ["5G", "Pro", "Lite", "Ultra", "Compact", "Flagship"], price: [249, 999],
    attrs: [
      variation("color", "Color", ["Black", "Titanium", "Silver", "Blue", "Graphite"]),
      variation("storage", "Storage", ["128 GB", "256 GB", "512 GB", "1 TB"]),
      variation("ram", "RAM", ["8 GB", "12 GB"]),
      spec("processor", "Processor", ["Nexa N3", "Nexa N4", "Nexa N5 Pro", "Zephyr Z2", "Zephyr Z3"], true),
      spec("processor_generation", "Processor generation", ["2nd generation", "3rd generation", "4th generation"]),
      spec("cpu_speed", "CPU speed", ["2.6 GHz", "2.9 GHz", "3.1 GHz", "3.3 GHz"]),
      spec("gpu", "GPU", ["Lumen G5", "Lumen G7", "Lumen G9"]),
      spec("display_size", "Display size", ["6.1 in", "6.4 in", "6.7 in", "6.9 in"], true),
      spec("refresh_rate", "Refresh rate", ["60 Hz", "90 Hz", "120 Hz", "144 Hz"], true),
      spec("storage_type", "Storage type", ["UFS 3.1", "UFS 4.0"], true),
      spec("battery", "Battery", ["4,300 mAh", "4,700 mAh", "5,000 mAh", "5,400 mAh"]),
      spec("material", "Frame material", ["Aluminium", "Titanium", "Stainless steel", "Glass and aluminium"], true),
      spec("connectivity", "Connectivity", ["5G, Wi-Fi 6E, Bluetooth 5.3", "5G, Wi-Fi 7, Bluetooth 5.4", "4G, Wi-Fi 6, Bluetooth 5.2"]),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["1 year limited", "2 years limited"]),
    ],
    deltas: { storage: { "128 GB": 0, "256 GB": 90, "512 GB": 210, "1 TB": 400 }, ram: { "8 GB": 0, "12 GB": 70 } },
    allowed: (s) => (s.ram === "8 GB" ? s.storage === "128 GB" || s.storage === "256 GB" : s.storage !== "128 GB"),
    features: ["Edge-to-edge OLED display with adaptive refresh rate", "Dual-camera system with night mode and optical stabilisation", "All-day battery with fast wired and wireless charging", "Face unlock and an in-display fingerprint reader", "Dual SIM with eSIM support", "Stereo speakers tuned for calls and video"],
    blurbs: ["A fast, well-built phone with a screen that holds up outdoors.", "A phone that keeps up with a long day and still fits one hand.", "Flagship-class performance without the flagship price."],
    uses: ["Ships with a USB-C cable and a SIM tool; the charger is sold separately.", "Unlocked and ready for any major carrier."],
  },
  {
    slug: "laptops", name: "Laptops", category: "electronics", shape: "laptop", noun: "Laptop",
    mods: ["Ultrabook", "Creator", "Everyday", "Gaming", "Business", "Thin and Light"], price: [449, 1799],
    attrs: [
      variation("color", "Color", ["Silver", "Graphite", "Midnight"]),
      variation("ram", "RAM", ["8 GB", "16 GB", "32 GB"]),
      variation("storage", "Storage", ["256 GB", "512 GB", "1 TB", "2 TB"]),
      spec("processor", "Processor", ["Nexa Core N5", "Nexa Core N7", "Nexa Core N9", "Zephyr Ryze 5", "Zephyr Ryze 7"], true),
      spec("processor_generation", "Processor generation", ["11th generation", "12th generation", "13th generation"]),
      spec("cpu_speed", "CPU speed", ["3.4 GHz", "4.2 GHz", "4.7 GHz", "5.0 GHz"]),
      spec("gpu", "GPU", ["Integrated graphics", "Lumen RX 4050", "Lumen RX 4060", "Lumen RX 4070"], true),
      spec("display", "Display", ["13.3 in, 1920 x 1200", "14 in, 2560 x 1600", "15.6 in, 1920 x 1080", "16 in, 2560 x 1600"], true),
      spec("refresh_rate", "Refresh rate", ["60 Hz", "120 Hz", "144 Hz"], true),
      spec("storage_type", "Storage type", ["NVMe SSD", "NVMe SSD (PCIe 4.0)"]),
      spec("operating_system", "Operating system", ["Linux", "Aurora OS", "Orbit OS"], true),
      spec("weight", "Weight", ["1.2 kg", "1.4 kg", "1.7 kg", "2.1 kg"]),
      spec("battery", "Battery", ["50 Wh", "60 Wh", "75 Wh", "90 Wh"]),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["1 year limited", "2 years limited"]),
    ],
    deltas: { ram: { "8 GB": 0, "16 GB": 110, "32 GB": 300 }, storage: { "256 GB": 0, "512 GB": 70, "1 TB": 180, "2 TB": 380 } },
    allowed: (s) => (s.ram === "8 GB" ? ["256 GB", "512 GB"].includes(s.storage) : s.ram === "16 GB" ? ["512 GB", "1 TB"].includes(s.storage) : ["1 TB", "2 TB"].includes(s.storage)),
    features: ["High-resolution display with thin bezels", "Backlit keyboard with a precise, quiet key feel", "Fast charging over USB-C", "Wi-Fi 6E and Bluetooth 5.3", "Aluminium chassis with a cool, quiet thermal design", "Webcam with a privacy shutter"],
    blurbs: ["A laptop that is quick for work and light enough for a bag.", "Strong performance in a chassis that does not shout about it.", "A balanced machine for study, work and the odd game."],
    uses: ["Ships with a USB-C charger and a quick-start guide.", "Memory and storage are fixed at purchase; choose the configuration you need."],
  },
  {
    slug: "tablets", name: "Tablets", category: "electronics", shape: "tablet", noun: "Tablet",
    mods: ["Pro", "Air", "Mini", "Family", "Paper-Feel"], price: [179, 899],
    attrs: [
      variation("color", "Color", ["Space Grey", "Silver", "Blue"]),
      variation("storage", "Storage", ["64 GB", "128 GB", "256 GB"]),
      variation("connectivity", "Connectivity", ["Wi-Fi", "Wi-Fi + Cellular"]),
      spec("processor", "Processor", ["Nexa N2 Tab", "Nexa N3 Tab", "Zephyr Z2 Tab"], true),
      spec("display_size", "Display size", ["8.3 in", "10.2 in", "10.9 in", "11 in", "12.9 in"], true),
      spec("refresh_rate", "Refresh rate", ["60 Hz", "90 Hz", "120 Hz"], true),
      spec("ram", "RAM", ["4 GB", "6 GB", "8 GB"]),
      spec("battery", "Battery life", ["10 hours", "12 hours", "14 hours"]),
      spec("stylus_support", "Stylus support", ["Yes", "No"], true),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["1 year limited", "2 years limited"]),
    ],
    deltas: { storage: { "64 GB": 0, "128 GB": 60, "256 GB": 150 }, connectivity: { "Wi-Fi": 0, "Wi-Fi + Cellular": 130 } },
    features: ["Bright, colour-accurate laminated display", "Quad speakers with spatial audio", "Front camera that keeps you centred on calls", "Support for a magnetic keyboard and a stylus (sold separately)", "USB-C with fast charging"],
    blurbs: ["A tablet that is as good for reading as it is for sketching.", "Light, fast and easy to pass around the sofa."],
    uses: ["Cellular models need a data plan from your carrier.", "Charger and cable included."],
  },
  {
    slug: "televisions", name: "Televisions", category: "electronics", shape: "tv", noun: "Television",
    mods: ["4K", "OLED", "QLED", "Smart", "Ultra HD"], price: [279, 1599],
    attrs: [
      variation("screen_size", "Screen size", ["43 in", "50 in", "55 in", "65 in", "75 in"]),
      spec("resolution", "Resolution", ["3840 x 2160 (4K)", "7680 x 4320 (8K)"], true),
      spec("panel_type", "Panel type", ["LED (VA)", "LED (IPS)", "QLED", "OLED"], true),
      spec("refresh_rate", "Refresh rate", ["60 Hz", "120 Hz", "144 Hz"], true),
      spec("hdr", "HDR formats", ["HDR10", "HDR10+ and Dolby-style HDR", "HDR10, HLG and dynamic HDR"]),
      spec("smart_platform", "Smart platform", ["Aurora TV", "Orbit TV", "Linux-based"]),
      spec("hdmi_ports", "HDMI ports", ["3 (1 with eARC)", "4 (2 with HDMI 2.1)"]),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["1 year limited", "2 years limited"]),
    ],
    deltas: { screen_size: { "43 in": 0, "50 in": 90, "55 in": 190, "65 in": 420, "75 in": 780 } },
    features: ["Dimming zones for deep blacks and bright highlights", "Game mode with auto low-latency", "Voice remote with a built-in microphone", "Wall-mount ready (mount sold separately)", "Built-in streaming apps and screen mirroring"],
    blurbs: ["A television with a picture that looks as good in daylight as at night.", "Big-screen viewing without a big-budget price."],
    uses: ["Table stand included in the box.", "Delivery includes unpacking at the door."],
  },
  {
    slug: "sofas", name: "Sofas", category: "furniture", shape: "sofa", noun: "Sofa",
    mods: ["Modular", "Three-Seat", "Two-Seat", "Corner", "Sleeper"], price: [349, 1899],
    attrs: [
      variation("color", "Color", ["Oat", "Charcoal", "Stone", "Navy"]),
      variation("material", "Upholstery", ["Woven fabric", "Performance fabric", "Leather"]),
      spec("dimensions", "Dimensions (W x D x H)", ["160 x 90 x 82 cm", "190 x 92 x 84 cm", "220 x 95 x 85 cm", "260 x 160 x 85 cm"]),
      spec("seating_capacity", "Seating capacity", ["2 seats", "3 seats", "4 seats"], true),
      spec("finish", "Leg finish", ["Natural oak", "Dark walnut", "Black powder-coat"], true),
      spec("frame", "Frame", ["Kiln-dried hardwood", "Engineered hardwood and plywood"]),
      spec("fill", "Seat fill", ["High-resilience foam", "Foam and feather wrap"]),
      spec("assembly", "Assembly", ["Legs only (10 minutes)", "Modular, no tools"]),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["2 years limited", "5 years on the frame"]),
    ],
    deltas: { material: { "Woven fabric": 0, "Performance fabric": 140, Leather: 520 } },
    features: ["Deep seat and supportive back cushions", "Removable covers on selected fabrics", "Solid wood legs", "Reinforced frame joints", "Fits through a standard doorway"],
    blurbs: ["A sofa that is comfortable to sit in and easy to live with.", "Simple lines, deep seats and covers you can actually clean."],
    uses: ["Delivered in two boxes; legs attach in minutes.", "Fabric swatches are not included; colours may vary slightly by screen."],
  },
  {
    slug: "office-chairs", name: "Office Chairs", category: "furniture", shape: "chair", noun: "Office Chair",
    mods: ["Ergonomic", "Mesh-Back", "Executive", "Task", "Adjustable"], price: [89, 549],
    attrs: [
      variation("color", "Color", ["Black", "Grey", "Navy"]),
      variation("material", "Back material", ["Mesh", "Fabric"]),
      spec("seat_height", "Seat height range", ["42 to 52 cm", "44 to 54 cm", "45 to 56 cm"]),
      spec("weight_capacity", "Weight capacity", ["120 kg", "136 kg", "150 kg"], true),
      spec("armrests", "Armrests", ["Fixed", "Height-adjustable", "4D adjustable"], true),
      spec("lumbar_support", "Lumbar support", ["Fixed", "Adjustable height", "Adjustable depth and height"]),
      spec("wheels", "Casters", ["Standard nylon", "Soft-roll for hard floors"]),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["2 years limited", "5 years limited"]),
    ],
    deltas: { material: { Mesh: 0, Fabric: 25 } },
    features: ["Synchro-tilt mechanism with a lockable recline", "Breathable back that follows the spine", "Gas lift rated for daily use", "Padded seat with a waterfall front edge", "Assembles with the included tool"],
    blurbs: ["A chair designed for a full working day.", "Supportive where it matters and adjustable where it counts."],
    uses: ["Arrives flat-packed; allow about 20 minutes to assemble.", "Backed by a manufacturer warranty."],
  },
  {
    slug: "running-shoes", name: "Running Shoes", category: "fashion", shape: "shoe", noun: "Running Shoes",
    mods: ["Road", "Trail", "Daily Trainer", "Lightweight", "Cushioned"], price: [59, 219],
    attrs: [
      variation("color", "Color", ["Black", "Grey", "White", "Navy"]),
      variation("size", "Size (US)", ["7", "8", "9", "10", "11", "12"]),
      spec("cushioning", "Cushioning", ["Responsive", "Maximum", "Balanced"], true),
      spec("drop", "Heel-to-toe drop", ["4 mm", "6 mm", "8 mm", "10 mm"]),
      spec("upper_material", "Upper", ["Engineered mesh", "Knit", "Breathable mesh with overlays"], true),
      spec("terrain", "Terrain", ["Road", "Trail", "Road and light trail"], true),
      spec("weight", "Weight (size 9)", ["230 g", "260 g", "290 g", "310 g"]),
      spec("fit", "Fit", ["True to size", "Runs slightly small", "Roomy forefoot"]),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["90-day fit guarantee"]),
    ],
    deltas: {},
    features: ["Foam midsole tuned for a smooth roll", "Outsole rubber placed where you wear it", "Breathable upper with a padded collar", "Reflective details for low light", "Removable insole"],
    blurbs: ["A shoe for the miles in between the races.", "Comfortable from the first run and durable enough for the hundredth."],
    uses: ["Free size exchange within 90 days.", "Sizing is US men's; order half a size down for women's sizing."],
  },
  {
    slug: "t-shirts", name: "T-Shirts", category: "fashion", shape: "tshirt", noun: "T-Shirt",
    mods: ["Heavyweight", "Organic Cotton", "Pocket", "Relaxed", "Classic Fit"], price: [14, 59],
    attrs: [
      variation("color", "Color", ["Black", "White", "Stone", "Navy", "Charcoal"]),
      variation("size", "Size", ["S", "M", "L", "XL"]),
      spec("material", "Material", ["100% organic cotton", "Cotton and modal", "Heavyweight cotton"], true),
      spec("fit", "Fit", ["Regular", "Relaxed", "Slim"], true),
      spec("neckline", "Neckline", ["Crew", "V-neck"]),
      spec("fabric_weight", "Fabric weight", ["160 gsm", "180 gsm", "220 gsm"]),
      spec("care", "Care", ["Machine wash cold", "Machine wash warm, tumble dry low"]),
      spec("model", "Model", []),
      spec("warranty", "Warranty", ["30-day returns"]),
    ],
    deltas: {},
    features: ["Pre-washed to limit shrinking", "Reinforced shoulder seams", "Tag-free neck label", "Dyed with low-impact dyes", "Holds its shape wash after wash"],
    blurbs: ["A t-shirt that gets better the more you wear it.", "Soft, substantial and cut to hang well."],
    uses: ["Order your usual size; see the size chart on the label.", "Free returns within 30 days."],
  },
];
